#!/usr/bin/env node
/**
 * dep_tree_js.js — Dependency tree analyzer for JS/TS packages.
 *
 * Usage:
 *   node dep_tree_js.js <project_path> <package_name> [--pkg-manager npm|yarn|pnpm|bun]
 *
 * Strategy (lockfile-first — IMPROVEMENTS #5):
 *   1. If a lockfile exists, parse it directly. This works even when
 *      node_modules/ is absent (Yarn 3 PnP / fresh checkout / CI-only install).
 *   2. Fall back to `<pm> ls --json` only when no lockfile is found.
 *
 * Output schema mirrors dep_tree.py so Phase 2 LLM logic stays shared:
 *   {
 *     "package_name": "lodash",
 *     "language": "javascript",
 *     "pkg_manager": "yarn",
 *     "current_version": "4.17.20",
 *     "dependency_type": "direct" | "transitive" | "both" | "peer" | "unknown",
 *     "is_direct": bool,
 *     "is_transitive": bool,
 *     "is_peer": bool,
 *     "parent_packages": ["express", ...],
 *     "version_constraints": { "express": "^4.17.0", "__declared__": "..." },
 *     "declared_in": ["dependencies", "devDependencies", ...],
 *     "source": "yarn3-lock" | "yarn1-lock" | "pnpm-lock" | "npm-lock" | "npm-ls" | "yarn-list",
 *     "full_tree": <raw>,
 *     "errors": []
 *   }
 *
 * No external npm deps required for lockfile parsing — uses custom parsers
 * for the YAML-ish formats (yarn 3 lockfile is YAML with key quirks; pnpm
 * lockfile is regular YAML but the small subset we need is parseable with
 * a hand-rolled reader).
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function parseArgs(argv) {
    const args = { projectPath: argv[2], packageName: argv[3], pkgManager: null };
    for (let i = 4; i < argv.length; i++) {
        if (argv[i] === '--pkg-manager' && argv[i + 1]) {
            args.pkgManager = argv[i + 1];
            i++;
        }
    }
    return args;
}

function detectLockfile(projectPath) {
    const candidates = [
        ['yarn.lock',          'yarn'],
        ['pnpm-lock.yaml',     'pnpm'],
        ['package-lock.json',  'npm'],
        ['npm-shrinkwrap.json','npm'],
        ['bun.lock',           'bun'],
        ['bun.lockb',          'bun'],
    ];
    for (const [name, pm] of candidates) {
        const full = path.join(projectPath, name);
        if (fs.existsSync(full)) return { path: full, pm, name };
    }
    return null;
}

function detectPkgManager(projectPath) {
    const lf = detectLockfile(projectPath);
    return lf ? lf.pm : 'npm';
}

function readManifest(projectPath) {
    const manifestPath = path.join(projectPath, 'package.json');
    if (!fs.existsSync(manifestPath)) {
        throw new Error(`package.json not found in ${projectPath}`);
    }
    return JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
}

const DEP_FIELDS = [
    'dependencies', 'devDependencies', 'peerDependencies', 'optionalDependencies',
];

function classifyDeclared(manifest, packageName) {
    const declaredIn = [];
    let declaredConstraint = null;
    for (const field of DEP_FIELDS) {
        if (manifest[field] && Object.prototype.hasOwnProperty.call(manifest[field], packageName)) {
            declaredIn.push(field);
            if (declaredConstraint === null) declaredConstraint = manifest[field][packageName];
        }
    }
    return { declaredIn, declaredConstraint };
}

/* ============================================================
 * Lockfile parsers
 *
 * Each parser returns:
 *   { entries: [{ name, version, dependencies: {name: range}, peers: {name: range} }],
 *     locator_to_resolved: Map<string, string> }
 * ============================================================ */

/** Detect whether a yarn.lock is yarn 1 (legacy) or yarn 2/3 (Berry).
 * Berry lockfiles start with `# This file is generated by running "yarn install"`
 * and contain `__metadata:` keys. */
function isYarnBerry(text) {
    return /^__metadata:/m.test(text) || /\n__metadata:\n/.test(text);
}

/**
 * Parse a yarn 2/3 (Berry) lockfile.
 * Format example (YAML-ish):
 *   "@scope/pkg@npm:^1.0.0":
 *     version: 1.2.3
 *     resolution: "@scope/pkg@npm:1.2.3"
 *     dependencies:
 *       lodash: ^4.17.0
 *     peerDependencies:
 *       react: ^18
 *     checksum: ...
 */
function parseYarnBerry(text) {
    const entries = [];
    // Split into entry blocks. Each entry starts at column-0 with a key line ending in ':'
    const lines = text.split('\n');
    let i = 0;
    while (i < lines.length) {
        const line = lines[i];
        // Skip blank / comment / __metadata
        if (!line || line.startsWith('#') || /^\s/.test(line) || line.startsWith('__metadata:')) {
            i++; continue;
        }
        // Entry header: e.g. `"lodash@npm:^4.17.0":` or `"@scope/pkg@npm:^1.0.0, @scope/pkg@npm:^1.1.0":`
        const headerMatch = /^("?)(.+?)\1:\s*$/.exec(line);
        if (!headerMatch) { i++; continue; }
        const locators = headerMatch[2].split(',').map(s => s.trim().replace(/^"|"$/g, ''));

        const entry = {
            locators,
            version: '',
            resolution: '',
            dependencies: {},
            peerDependencies: {},
        };

        i++;
        // Read indented body
        while (i < lines.length && /^\s/.test(lines[i])) {
            const bodyLine = lines[i];
            const trimmed = bodyLine.trim();
            if (!trimmed) { i++; continue; }

            if (/^version:\s*/.test(trimmed)) {
                entry.version = trimmed.replace(/^version:\s*/, '').replace(/^"|"$/g, '').trim();
            } else if (/^resolution:\s*/.test(trimmed)) {
                entry.resolution = trimmed.replace(/^resolution:\s*/, '').replace(/^"|"$/g, '').trim();
            } else if (/^(dependencies|peerDependencies|optionalDependencies):\s*$/.test(trimmed)) {
                const section = trimmed.split(':')[0];
                i++;
                while (i < lines.length && /^\s{4,}/.test(lines[i])) {
                    const depLine = lines[i].trim();
                    if (!depLine) { i++; continue; }
                    const dm = /^("?)(.+?)\1:\s*("?)(.+?)\3\s*$/.exec(depLine);
                    if (dm) {
                        const depName = dm[2];
                        const range = dm[4];
                        if (section === 'peerDependencies') {
                            entry.peerDependencies[depName] = range;
                        } else {
                            entry.dependencies[depName] = range;
                        }
                    }
                    i++;
                }
                continue;
            }
            i++;
        }
        // Derive name from the first locator (`name@protocol:range`)
        const firstLoc = entry.locators[0] || '';
        const nm = /^((?:@[^/]+\/)?[^@]+)@/.exec(firstLoc);
        entry.name = nm ? nm[1] : firstLoc;
        entries.push(entry);
    }
    return { entries, format: 'yarn3-lock' };
}

/**
 * Parse a yarn 1 (legacy) lockfile.
 * Format example:
 *   lodash@^4.17.0:
 *     version "4.17.21"
 *     resolved "https://..."
 *     integrity sha512-...
 *     dependencies:
 *       "is-arrayish" "^0.3.0"
 */
function parseYarn1(text) {
    const entries = [];
    const lines = text.split('\n');
    let i = 0;
    while (i < lines.length) {
        const line = lines[i];
        if (!line || line.startsWith('#') || /^\s/.test(line)) { i++; continue; }
        // Header: "lodash@^4.17.0:" or `"@scope/pkg@^1.0.0":` or "a@x, a@y:"
        const headerMatch = /^(.+):\s*$/.exec(line);
        if (!headerMatch) { i++; continue; }
        const locators = headerMatch[1].split(',').map(s => s.trim().replace(/^"|"$/g, ''));
        const entry = { locators, version: '', resolved: '', dependencies: {}, peerDependencies: {} };
        i++;
        while (i < lines.length && /^\s/.test(lines[i])) {
            const trimmed = lines[i].trim();
            if (!trimmed) { i++; continue; }
            const vm = /^version\s+"([^"]+)"/.exec(trimmed);
            if (vm) { entry.version = vm[1]; i++; continue; }
            if (/^dependencies:\s*$/.test(trimmed) || /^peerDependencies:\s*$/.test(trimmed)
                || /^optionalDependencies:\s*$/.test(trimmed)) {
                const section = trimmed.split(':')[0];
                i++;
                while (i < lines.length && /^\s{4,}/.test(lines[i])) {
                    const depLine = lines[i].trim();
                    const dm = /^"?([^"\s]+)"?\s+"?([^"]+)"?$/.exec(depLine);
                    if (dm) {
                        if (section === 'peerDependencies') entry.peerDependencies[dm[1]] = dm[2];
                        else entry.dependencies[dm[1]] = dm[2];
                    }
                    i++;
                }
                continue;
            }
            i++;
        }
        const firstLoc = entry.locators[0] || '';
        const nm = /^((?:@[^/]+\/)?[^@]+)@/.exec(firstLoc);
        entry.name = nm ? nm[1] : firstLoc;
        entries.push(entry);
    }
    return { entries, format: 'yarn1-lock' };
}

/**
 * Parse a pnpm-lock.yaml.
 * Format excerpt (we only need the `packages:` map):
 *   packages:
 *     /lodash@4.17.21:
 *       resolution: {integrity: sha512-...}
 *       dependencies:
 *         is-arrayish: 0.3.2
 *       peerDependencies:
 *         react: '>=16'
 */
function parsePnpm(text) {
    const entries = [];
    // Find the `packages:` block
    const pkgIdx = text.indexOf('\npackages:');
    if (pkgIdx < 0) return { entries, format: 'pnpm-lock' };
    const tail = text.slice(pkgIdx);
    const lines = tail.split('\n');
    let i = 1; // skip "packages:" header line itself
    while (i < lines.length) {
        const line = lines[i];
        // Top-level key is 2-space indented under `packages:` (lockfile v6/v7 quote-wrapped)
        const keyMatch = /^  ['"]?(\/?[^'"]+?)['"]?:\s*$/.exec(line);
        if (!keyMatch) { i++; continue; }
        const fullKey = keyMatch[1]; // e.g. "/lodash@4.17.21" or "/@scope/pkg@1.0.0(react@18)"
        const stripped = fullKey.replace(/^\//, '');
        // Strip peer-id suffix like `(react@18)`
        const noPeer = stripped.replace(/\(.+?\)$/, '');
        const m = /^((?:@[^/]+\/)?[^@]+)@(.+)$/.exec(noPeer);
        if (!m) { i++; continue; }
        const entry = { locators: [fullKey], name: m[1], version: m[2],
                        dependencies: {}, peerDependencies: {} };
        i++;
        while (i < lines.length && /^    /.test(lines[i])) {
            const trimmed = lines[i].trim();
            if (!trimmed) { i++; continue; }
            if (/^dependencies:\s*$/.test(trimmed) || /^peerDependencies:\s*$/.test(trimmed)
                || /^optionalDependencies:\s*$/.test(trimmed)) {
                const section = trimmed.split(':')[0];
                i++;
                while (i < lines.length && /^      /.test(lines[i])) {
                    const dl = lines[i].trim();
                    const dm = /^([^:]+):\s*(.+?)\s*$/.exec(dl);
                    if (dm) {
                        const depName = dm[1].replace(/^['"]|['"]$/g, '');
                        const range = dm[2].replace(/^['"]|['"]$/g, '');
                        if (section === 'peerDependencies') entry.peerDependencies[depName] = range;
                        else entry.dependencies[depName] = range;
                    }
                    i++;
                }
                continue;
            }
            i++;
        }
        entries.push(entry);
    }
    return { entries, format: 'pnpm-lock' };
}

/**
 * Parse a package-lock.json (npm v7+).
 * Format: { "packages": { "node_modules/lodash": { "version": ..., "dependencies": {...} } } }
 */
function parseNpmLock(jsonStr) {
    const data = JSON.parse(jsonStr);
    const entries = [];
    const pkgs = data.packages || {};
    for (const [key, val] of Object.entries(pkgs)) {
        if (key === '') continue; // root entry
        // key looks like "node_modules/lodash" or "node_modules/@scope/pkg" or "node_modules/parent/node_modules/lodash"
        const m = /node_modules\/((?:@[^/]+\/)?[^/]+)$/.exec(key);
        if (!m) continue;
        const name = m[1];
        entries.push({
            locators: [key],
            name,
            version: val.version || '',
            dependencies: val.dependencies || {},
            peerDependencies: val.peerDependencies || {},
            dev: !!val.dev,
        });
    }
    return { entries, format: 'npm-lock' };
}

/* ============================================================
 * Common collector: given the parsed lockfile, find every package
 * that lists `target` in its `dependencies`/`peerDependencies`.
 * ============================================================ */

function collectParentsFromLock(parsed, target, rootName) {
    const parents = new Set();
    const constraints = {};
    for (const entry of parsed.entries) {
        // Skip workspace root resolutions (`<name>@workspace:...`) — those
        // aren't "parent packages" in the dep-graph sense; they are the
        // manifest the user already controls.
        const isWorkspace = (entry.locators || []).some(l => /@workspace:/.test(l));
        if (isWorkspace) continue;
        if (entry.dependencies && entry.dependencies[target] !== undefined) {
            parents.add(entry.name);
            // Prefer the first (closest) constraint encountered
            if (!constraints[entry.name]) constraints[entry.name] = entry.dependencies[target];
        }
        if (entry.peerDependencies && entry.peerDependencies[target] !== undefined) {
            parents.add(entry.name);
            if (!constraints[entry.name]) constraints[entry.name] = entry.peerDependencies[target] + ' (peer)';
        }
    }
    // Remove self-references and root manifest name
    parents.delete(target);
    if (rootName) parents.delete(rootName);
    return { parents: Array.from(parents), constraints };
}

function getInstalledVersionFromLock(parsed, target) {
    // Return the first version we see for target (lockfiles may have multiple)
    for (const entry of parsed.entries) {
        if (entry.name === target && entry.version) return entry.version;
    }
    return 'unknown';
}

/* ============================================================
 * Fallback: package-manager `ls`-based tree (existing behavior).
 * Kept for the rare case where no lockfile exists.
 * ============================================================ */

function getTreeNpmFallback(projectPath) {
    try {
        const out = execSync('npm ls --all --json', {
            cwd: projectPath, stdio: ['ignore', 'pipe', 'pipe'],
            maxBuffer: 1024 * 1024 * 128,
        }).toString();
        return { format: 'npm-ls', data: JSON.parse(out) };
    } catch (err) {
        if (err.stdout && err.stdout.length > 0) {
            try { return { format: 'npm-ls', data: JSON.parse(err.stdout.toString()) }; } catch (_) { /* */ }
        }
        return { format: 'npm-ls', data: null, error: err.message };
    }
}

function walkNpmTreeJSON(node, target, parents, constraints, parentName) {
    if (!node || typeof node !== 'object') return;
    const deps = node.dependencies || {};
    for (const [depName, depNode] of Object.entries(deps)) {
        if (depName === target && parentName && !parents.has(parentName)) {
            parents.add(parentName);
            const peer = (depNode && depNode.peer) ? ' (peer)' : '';
            const required = (depNode && depNode.required) ||
                             (depNode && depNode.from) ||
                             (depNode && depNode.version ? `==${depNode.version}` : '');
            constraints[parentName] = `${required}${peer}` || 'unknown';
        }
        walkNpmTreeJSON(depNode, target, parents, constraints, depName);
    }
}

/* ============================================================
 * Main
 * ============================================================ */

function main() {
    const args = parseArgs(process.argv);
    if (!args.projectPath || !args.packageName) {
        process.stderr.write('Usage: node dep_tree_js.js <project_path> <package_name> [--pkg-manager npm|yarn|pnpm|bun]\n');
        process.exit(1);
    }

    const errors = [];
    const pkgManager = args.pkgManager || detectPkgManager(args.projectPath);

    let manifest;
    try {
        manifest = readManifest(args.projectPath);
    } catch (err) {
        process.stdout.write(JSON.stringify({
            package_name: args.packageName,
            language: 'javascript',
            pkg_manager: pkgManager,
            error: err.message,
        }, null, 2) + '\n');
        process.exit(1);
    }

    const { declaredIn, declaredConstraint } = classifyDeclared(manifest, args.packageName);

    // ---- Lockfile-first ----
    const lockfile = detectLockfile(args.projectPath);
    let parents = [];
    let constraints = {};
    let installedVersion = 'unknown';
    let source = 'unknown';
    let fullTree = null;

    if (lockfile) {
        const text = fs.readFileSync(lockfile.path, 'utf8');
        let parsed;
        try {
            if (lockfile.pm === 'yarn') {
                parsed = isYarnBerry(text) ? parseYarnBerry(text) : parseYarn1(text);
            } else if (lockfile.pm === 'pnpm') {
                parsed = parsePnpm(text);
            } else if (lockfile.pm === 'npm') {
                parsed = parseNpmLock(text);
            } else if (lockfile.pm === 'bun') {
                // bun.lock(b): no robust parser without bun runtime; record as unsupported
                errors.push('bun lockfile parsing not implemented yet; falling back to package.json declaration only');
                parsed = { entries: [], format: 'bun-unsupported' };
            }
            source = parsed.format;
            const collected = collectParentsFromLock(parsed, args.packageName, manifest.name);
            parents = collected.parents;
            constraints = collected.constraints;
            installedVersion = getInstalledVersionFromLock(parsed, args.packageName);
            fullTree = { format: parsed.format, entry_count: parsed.entries.length };
        } catch (err) {
            errors.push(`lockfile parse failed: ${err.message}`);
        }
    }

    // ---- Fallback to `npm ls` if no lockfile or parse failed AND node_modules exists ----
    const hasNodeModules = fs.existsSync(path.join(args.projectPath, 'node_modules'));
    if ((!lockfile || installedVersion === 'unknown') && pkgManager === 'npm' && hasNodeModules) {
        const tree = getTreeNpmFallback(args.projectPath);
        if (tree.data) {
            source = source === 'unknown' ? 'npm-ls' : `${source}+npm-ls`;
            const ps = new Set();
            walkNpmTreeJSON(tree.data, args.packageName, ps, constraints, null);
            for (const p of ps) if (!parents.includes(p)) parents.push(p);
            fullTree = fullTree || tree.data;
        }
        if (tree.error) errors.push(`npm ls fallback: ${tree.error}`);
    }

    const isDirect = declaredIn.length > 0 && !declaredIn.every(f => f === 'peerDependencies');
    const isPeer = declaredIn.includes('peerDependencies');
    const isTransitive = parents.length > 0;

    let depType = 'unknown';
    if (isDirect && isTransitive) depType = 'both';
    else if (isDirect)            depType = 'direct';
    else if (isTransitive)        depType = 'transitive';
    else if (isPeer)              depType = 'peer';

    if (declaredConstraint !== null) constraints.__declared__ = declaredConstraint;

    const result = {
        package_name: args.packageName,
        language: 'javascript',
        pkg_manager: pkgManager,
        current_version: installedVersion,
        dependency_type: depType,
        is_direct: isDirect,
        is_transitive: isTransitive,
        is_peer: isPeer,
        parent_packages: parents,
        version_constraints: constraints,
        declared_in: declaredIn,
        source,
        full_tree: fullTree,
        errors,
    };

    process.stdout.write(JSON.stringify(result, null, 2) + '\n');
}

main();
